"""empty message

Revision ID: c4c5a928e6ba
Revises: 66dbf6c63c59
Create Date: 2025-04-22 20:05:18.634066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c5a928e6ba'
down_revision = '66dbf6c63c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['filename'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
