"""empty message

Revision ID: fb22afda156f
Revises: 
Create Date: 2025-04-23 17:50:50.812515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb22afda156f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('data_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_file_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('stats_mean', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_median', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_correlation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_std', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_min', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats_max', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('missing_values_filled', sa.Integer(), nullable=True),
    sa.Column('cleaning_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['data_file_id'], ['data_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('plot_type', sa.String(length=50), nullable=True),
    sa.Column('plot_data', sa.LargeBinary(), nullable=True),
    sa.Column('plot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('columns_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['data_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_plots')
    op.drop_table('data_analyses')
    op.drop_table('data_files')
    # ### end Alembic commands ###
